// Generated by gencpp from file kinematics_legged/bezier.msg
// DO NOT EDIT!


#ifndef KINEMATICS_LEGGED_MESSAGE_BEZIER_H
#define KINEMATICS_LEGGED_MESSAGE_BEZIER_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Float32.h>
#include <std_msgs/Float32.h>
#include <std_msgs/Float32.h>

namespace kinematics_legged
{
template <class ContainerAllocator>
struct bezier_
{
  typedef bezier_<ContainerAllocator> Type;

  bezier_()
    : x()
    , y()
    , z()  {
    }
  bezier_(const ContainerAllocator& _alloc)
    : x(_alloc)
    , y(_alloc)
    , z(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::std_msgs::Float32_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::std_msgs::Float32_<ContainerAllocator> >> _x_type;
  _x_type x;

   typedef std::vector< ::std_msgs::Float32_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::std_msgs::Float32_<ContainerAllocator> >> _y_type;
  _y_type y;

   typedef std::vector< ::std_msgs::Float32_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::std_msgs::Float32_<ContainerAllocator> >> _z_type;
  _z_type z;





  typedef boost::shared_ptr< ::kinematics_legged::bezier_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::kinematics_legged::bezier_<ContainerAllocator> const> ConstPtr;

}; // struct bezier_

typedef ::kinematics_legged::bezier_<std::allocator<void> > bezier;

typedef boost::shared_ptr< ::kinematics_legged::bezier > bezierPtr;
typedef boost::shared_ptr< ::kinematics_legged::bezier const> bezierConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::kinematics_legged::bezier_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::kinematics_legged::bezier_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::kinematics_legged::bezier_<ContainerAllocator1> & lhs, const ::kinematics_legged::bezier_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.z == rhs.z;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::kinematics_legged::bezier_<ContainerAllocator1> & lhs, const ::kinematics_legged::bezier_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace kinematics_legged

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::kinematics_legged::bezier_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kinematics_legged::bezier_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kinematics_legged::bezier_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kinematics_legged::bezier_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kinematics_legged::bezier_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kinematics_legged::bezier_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::kinematics_legged::bezier_<ContainerAllocator> >
{
  static const char* value()
  {
    return "091cca004b733810eb3a4ffef5db3158";
  }

  static const char* value(const ::kinematics_legged::bezier_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x091cca004b733810ULL;
  static const uint64_t static_value2 = 0xeb3a4ffef5db3158ULL;
};

template<class ContainerAllocator>
struct DataType< ::kinematics_legged::bezier_<ContainerAllocator> >
{
  static const char* value()
  {
    return "kinematics_legged/bezier";
  }

  static const char* value(const ::kinematics_legged::bezier_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::kinematics_legged::bezier_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Float32[] x\n"
"std_msgs/Float32[] y\n"
"std_msgs/Float32[] z\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Float32\n"
"float32 data\n"
;
  }

  static const char* value(const ::kinematics_legged::bezier_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::kinematics_legged::bezier_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct bezier_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::kinematics_legged::bezier_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::kinematics_legged::bezier_<ContainerAllocator>& v)
  {
    s << indent << "x[]" << std::endl;
    for (size_t i = 0; i < v.x.size(); ++i)
    {
      s << indent << "  x[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::std_msgs::Float32_<ContainerAllocator> >::stream(s, indent + "    ", v.x[i]);
    }
    s << indent << "y[]" << std::endl;
    for (size_t i = 0; i < v.y.size(); ++i)
    {
      s << indent << "  y[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::std_msgs::Float32_<ContainerAllocator> >::stream(s, indent + "    ", v.y[i]);
    }
    s << indent << "z[]" << std::endl;
    for (size_t i = 0; i < v.z.size(); ++i)
    {
      s << indent << "  z[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::std_msgs::Float32_<ContainerAllocator> >::stream(s, indent + "    ", v.z[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // KINEMATICS_LEGGED_MESSAGE_BEZIER_H
