# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from kinematics_legged/bezier.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import std_msgs.msg

class bezier(genpy.Message):
  _md5sum = "091cca004b733810eb3a4ffef5db3158"
  _type = "kinematics_legged/bezier"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """std_msgs/Float32[] x
std_msgs/Float32[] y
std_msgs/Float32[] z

================================================================================
MSG: std_msgs/Float32
float32 data"""
  __slots__ = ['x','y','z']
  _slot_types = ['std_msgs/Float32[]','std_msgs/Float32[]','std_msgs/Float32[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       x,y,z

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(bezier, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.x is None:
        self.x = []
      if self.y is None:
        self.y = []
      if self.z is None:
        self.z = []
    else:
      self.x = []
      self.y = []
      self.z = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      length = len(self.x)
      buff.write(_struct_I.pack(length))
      for val1 in self.x:
        _x = val1.data
        buff.write(_get_struct_f().pack(_x))
      length = len(self.y)
      buff.write(_struct_I.pack(length))
      for val1 in self.y:
        _x = val1.data
        buff.write(_get_struct_f().pack(_x))
      length = len(self.z)
      buff.write(_struct_I.pack(length))
      for val1 in self.z:
        _x = val1.data
        buff.write(_get_struct_f().pack(_x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.x is None:
        self.x = None
      if self.y is None:
        self.y = None
      if self.z is None:
        self.z = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.x = []
      for i in range(0, length):
        val1 = std_msgs.msg.Float32()
        start = end
        end += 4
        (val1.data,) = _get_struct_f().unpack(str[start:end])
        self.x.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.y = []
      for i in range(0, length):
        val1 = std_msgs.msg.Float32()
        start = end
        end += 4
        (val1.data,) = _get_struct_f().unpack(str[start:end])
        self.y.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.z = []
      for i in range(0, length):
        val1 = std_msgs.msg.Float32()
        start = end
        end += 4
        (val1.data,) = _get_struct_f().unpack(str[start:end])
        self.z.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      length = len(self.x)
      buff.write(_struct_I.pack(length))
      for val1 in self.x:
        _x = val1.data
        buff.write(_get_struct_f().pack(_x))
      length = len(self.y)
      buff.write(_struct_I.pack(length))
      for val1 in self.y:
        _x = val1.data
        buff.write(_get_struct_f().pack(_x))
      length = len(self.z)
      buff.write(_struct_I.pack(length))
      for val1 in self.z:
        _x = val1.data
        buff.write(_get_struct_f().pack(_x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.x is None:
        self.x = None
      if self.y is None:
        self.y = None
      if self.z is None:
        self.z = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.x = []
      for i in range(0, length):
        val1 = std_msgs.msg.Float32()
        start = end
        end += 4
        (val1.data,) = _get_struct_f().unpack(str[start:end])
        self.x.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.y = []
      for i in range(0, length):
        val1 = std_msgs.msg.Float32()
        start = end
        end += 4
        (val1.data,) = _get_struct_f().unpack(str[start:end])
        self.y.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.z = []
      for i in range(0, length):
        val1 = std_msgs.msg.Float32()
        start = end
        end += 4
        (val1.data,) = _get_struct_f().unpack(str[start:end])
        self.z.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_f = None
def _get_struct_f():
    global _struct_f
    if _struct_f is None:
        _struct_f = struct.Struct("<f")
    return _struct_f
